[package]
name = "darklua"
version = "0.4.0"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Transform Lua 5.1 scripts"
repository = "https://gitlab.com/jeparlefrancais/darklua"
license = "MIT"
keywords = ["lua", "obsfucation", "minify"]

[badges]
gitlab = { repository = "jeparlefrancais/darklua" }

[lib]
name = "darklua_core"
path = "src/lib.rs"

[[bin]]
name = "darklua"
path = "src/bin.rs"

[dependencies]
structopt = "0.3.9"
luaparser = { version = "0.1.1", default-features = false }
serde = "1.0"
json5 = "0.2"

[dev-dependencies]
insta = "1.6"
rand = "0.7.3"
rand_distr = "0.2.2"
